# Generated by Django 5.0.14 on 2026-06-16 13:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='buildings/icons/', verbose_name='Иконка для списка')),
                ('category', models.CharField(choices=[('extraction', 'Добыча'), ('production', 'Производство'), ('energy', 'Энергетика'), ('logistics', 'Логистика'), ('storage', 'Хранение'), ('special', 'Особые')], max_length=20, verbose_name='Категория')),
                ('base_power', models.FloatField(default=0, verbose_name='Базовая мощность (МВт)')),
                ('connection_slots', models.IntegerField(default=0, verbose_name='Слотов энергоподключения')),
                ('supports_overclock', models.BooleanField(default=False, verbose_name='Поддержка разгона')),
            ],
            options={
                'verbose_name': 'Здание',
                'verbose_name_plural': 'Здания',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('icon', models.ImageField(upload_to='items/', verbose_name='Иконка')),
                ('is_liquid', models.BooleanField(default=False, verbose_name='Жидкость или газ')),
                ('is_raw', models.BooleanField(default=False, verbose_name='Сырьё (добывается)')),
                ('tier', models.IntegerField(default=0, verbose_name='Уровень')),
                ('extraction_rate', models.FloatField(blank=True, null=True, verbose_name='Базовая скорость добычи (ед/мин, для бедного месторождения)')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
                'ordering': ['tier', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BuildingPort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'Вход'), ('output', 'Выход')], max_length=10, verbose_name='Направление')),
                ('accepted_form', models.CharField(choices=[('solid', 'Твёрдое'), ('liquid', 'Жидкость/Газ')], max_length=10, verbose_name='Форма ресурса')),
                ('label', models.CharField(blank=True, max_length=50, verbose_name='Метка')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ports', to='planner.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Порт здания',
                'verbose_name_plural': 'Порты зданий',
                'ordering': ['direction', 'label'],
            },
        ),
        migrations.CreateModel(
            name='PlacedBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(verbose_name='X')),
                ('y', models.IntegerField(verbose_name='Y')),
                ('overclock', models.FloatField(default=1.0, verbose_name='Разгон (1.0 = 100%)')),
                ('somersloop_active', models.BooleanField(default=False, verbose_name='Петлевик активен (удвоение выхода, ×4 энергии)')),
                ('is_external_input', models.BooleanField(default=False, verbose_name='Внешний ввод')),
                ('external_rate', models.FloatField(blank=True, null=True, verbose_name='Объём внешнего ввода (ед/мин)')),
                ('resource_purity', models.FloatField(blank=True, null=True, verbose_name='Богатство месторождения (0.5/1.0/2.0)')),
                ('splitter_config', models.JSONField(blank=True, null=True, verbose_name='Настройка разветвителя: {"left": item_id|"any"|"overflow", ...}')),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.building', verbose_name='Тип здания')),
                ('external_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='external_sources', to='planner.item', verbose_name='Предмет внешнего ввода')),
            ],
            options={
                'verbose_name': 'Размещённое здание',
                'verbose_name_plural': 'Размещённые здания',
            },
        ),
        migrations.CreateModel(
            name='PortInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.buildingport', verbose_name='Порт здания')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.item', verbose_name='Фактический ресурс')),
                ('placed_building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='port_instances', to='planner.placedbuilding', verbose_name='Размещённое здание')),
            ],
            options={
                'verbose_name': 'Экземпляр порта',
                'verbose_name_plural': 'Экземпляры портов',
                'unique_together': {('placed_building', 'building_port')},
            },
        ),
        migrations.CreateModel(
            name='ProductionLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('mma_power_slots', models.BooleanField(default=False, verbose_name='Улучшение MMA: доп. энергослоты')),
                ('is_published', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('total_power', models.FloatField(default=0, verbose_name='Потребление (МВт)')),
                ('total_buildings', models.IntegerField(default=0, verbose_name='Всего зданий')),
                ('layout_json', models.JSONField(default=dict, verbose_name='Схема линии')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Производственная линия',
                'verbose_name_plural': 'Производственные линии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='placedbuilding',
            name='line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placed_buildings', to='planner.productionline', verbose_name='Линия'),
        ),
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('connection_type', models.CharField(choices=[('belt', 'Конвейер'), ('pipe', 'Труба'), ('power', 'Энергокабель')], default='belt', max_length=10, verbose_name='Тип соединения')),
                ('belt_level', models.IntegerField(blank=True, null=True, verbose_name='Уровень конвейера (Mk.1–Mk.5)')),
                ('pipe_level', models.IntegerField(blank=True, null=True, verbose_name='Уровень трубы (Mk.1–Mk.2)')),
                ('from_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='output_connections', to='planner.portinstance', verbose_name='От порта')),
                ('to_port', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_connections', to='planner.portinstance', verbose_name='К порту')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='connections', to='planner.productionline', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Соединение',
                'verbose_name_plural': 'Соединения',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarked_by', to='planner.productionline', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Закладка',
                'verbose_name_plural': 'Закладки',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('base_duration', models.FloatField(verbose_name='Длительность цикла (сек)')),
                ('is_alternative', models.BooleanField(default=False, verbose_name='Альтернативный')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to='planner.building', verbose_name='Здание')),
            ],
            options={
                'verbose_name': 'Рецепт',
                'verbose_name_plural': 'Рецепты',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='placedbuilding',
            name='recipe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='planner.recipe', verbose_name='Рецепт'),
        ),
        migrations.CreateModel(
            name='RecipeRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('input', 'Вход'), ('output', 'Выход')], max_length=10, verbose_name='Направление')),
                ('amount', models.FloatField(verbose_name='Количество за цикл')),
                ('is_waste', models.BooleanField(default=False, verbose_name='Побочный продукт (требует обязательного вывода)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.item', verbose_name='Предмет')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='planner.recipe', verbose_name='Рецепт')),
            ],
            options={
                'verbose_name': 'Требование рецепта',
                'verbose_name_plural': 'Требования рецептов',
                'ordering': ['direction', 'item__name'],
            },
        ),
        migrations.CreateModel(
            name='LineOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.FloatField(verbose_name='Объём (ед/мин)')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.item', verbose_name='Предмет')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outputs', to='planner.productionline', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Итоговый ресурс',
                'verbose_name_plural': 'Итоговые ресурсы',
                'unique_together': {('line', 'item')},
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='planner.productionline', verbose_name='Линия')),
            ],
            options={
                'verbose_name': 'Лайк',
                'verbose_name_plural': 'Лайки',
                'unique_together': {('user', 'line')},
            },
        ),
        migrations.AddConstraint(
            model_name='connection',
            constraint=models.CheckConstraint(check=models.Q(('from_port', models.F('to_port')), _negated=True), name='no_self_connection'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('user', 'line')},
        ),
    ]
