# Generated by Django 5.0.14 on 2026-06-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='building',
            name='building_cost',
            field=models.JSONField(blank=True, null=True, verbose_name='Стоимость постройки'),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_type',
            field=models.CharField(choices=[('belt', 'Конвейер'), ('pipe', 'Труба'), ('power', 'Энергокабель'), ('well', 'Скважинное соединение')], default='belt', max_length=10, verbose_name='Тип соединения'),
        ),
    ]
