# Generated by Django 5.0.14 on 2026-06-16 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_building_building_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='building',
            name='building_cost',
        ),
        migrations.CreateModel(
            name='BuildingCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(verbose_name='Количество')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='planner.building', verbose_name='Здание')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.item', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Стоимость здания',
                'verbose_name_plural': 'Стоимость зданий',
                'unique_together': {('building', 'item')},
            },
        ),
    ]
