# Generated by Django 5.0.14 on 2026-06-18 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_remove_building_building_cost_buildingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='max_power',
            field=models.FloatField(default=0.0, verbose_name='Макс. энергопотребление (МВт)'),
        ),
    ]
