# Generated by Django 5.0.14 on 2026-06-18 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_recipe_max_power'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='energy_value',
            field=models.FloatField(default=0.0, verbose_name='Энергоёмкость (МДж)'),
        ),
        migrations.CreateModel(
            name='GeneratorFuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_types', to='planner.building', verbose_name='Генератор')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='used_in_generators', to='planner.item', verbose_name='Топливо')),
            ],
            options={
                'verbose_name': 'Топливо генератора',
                'verbose_name_plural': 'Топливо генераторов',
                'unique_together': {('building', 'item')},
            },
        ),
    ]
